### ISSUE TITLE
Weighted means 

### ISSUE THREAD

**Issue by fpbarthel** [zd1/telseq#1]
Hi,

In the readme you say "Merge results from read groups by taking a weighted mean. However, it is benetifical run without -m to output the result per lane, so to have an idea about inter-lane variation. The merging can be done afterwards."

How to do the merging afterwards?

Thanks

**Comment by zd1** [comment]
Once the results for individual lanes are obtained, they can be combined as one wishes, e.g. taking average or weighted average. If -m then only the combined information, which was done by taking the weighted average, is produced.

**Comment by fpbarthel** [comment]
Thanks, I understood up to this point, what I was wondering is what variable to use as weights. I used 'mapped' but it isn't clear from the documentation if this is the right one.

**Comment by zd1** [comment]
Sure, I used the total number of reads for this.

**Comment by fpbarthel** [comment]
Great, thanks, does it really matter then?
