### ISSUE TITLE
Estimating telomere length for other organisms

### ISSUE THREAD

**Issue by danshu** [zd1/telseq#11]
Hi,

I would like to use Telseq to estimate telomere lengths of other organisms. As I can understand, the only difference in calculation is c, the constant for genome length divided by number of telomere ends, which should be organism specific. I can not find options for setting genome length and chromosome number, so the default output should be of human.

So can I simply calculate using the following formula?
telomere_length_of_my organism=LENGTH_ESTIMATE (default output) / c_human \* c_my_organism

Best,
Quan

**Comment by zd1** [comment]
Hi Quan, take a look at the constants in this header file https://github.com/zd1/telseq/blob/master/src/Telseq/telseq.h
You could change the values of GENOME_LENGTH_AT_TEL_GC and TELOMERE_ENDS. 

Best,
Zhihao

**Comment by danshu** [comment]
Hi Zhihao,

GENOME_LENGTH_AT_TEL_GC is the cumulative length of genomic regions with the same GC composition (between 48 and 52%). I would like to know how do you get this length. Is the complete genome sequence required? 

Thanks,
Quan

**Comment by danshu** [comment]
@zd1 Any idea on my previous question?

**Comment by zd1** [comment]
Hi Quan, I forgot that I haven't replied, sorry for the delay. To obtain the length, I scan the genome using a 100bp window and count the number of windows that have a GC composition in the range of 48% to 52%. The sum of the length of these windows is the value of that variable.  For a new organism, this is not necessarily a major factor contributing to the noise. You could skip this step and just use the total genome length as a start. 

Best, 
Zhihao

**Comment by danshu** [comment]
@zd1 Thanks for your explanation!

**Comment by mehmetdayi** [comment]
Hi,

I am using TelSeq for a newly sequenced organism. I am able to get results, but It would be great if I could get telomere positions per chromosome. How can I do that? 

Thanks.
