### ISSUE TITLE
Use telseq on other genome?

### ISSUE THREAD

**Issue by kumatang** [zd1/telseq#13]
Hi,

It seems that telseq is based on human genome, I use telseq on C.elegans, but the estimate length is much higher than the the average length of this organism, so how should I get the true length?

Thanks.

**Comment by zd1** [comment]
Hi there, you could try to change the genome length constant defined in telseq/src/Telseq/telseq.h. However, I haven't done this for C.elegans so don't know if that's sufficient. Alternatively, I think it'd be better to use a relative length compared against control samples. 

Cheers,
Zhihao

**Comment by melop** [comment]
Dear Zhihao,

      I have the same question: I am trying to run telseq on organisms with different number of chromosomes. Currently this is the code for computing the length estimate:

(acc/gc_tel)*float(ScanParameters::GENOME_LENGTH_AT_TEL_GC)/ScanParameters::LENGTH_UNIT/ScanParameters::TELOMERE_ENDS;

    I know that TELOMERE_ENDS is the number of haploid human chromosome ends (this is set to 46), LENGTH_UNIT is 1000, acc is the telomeric read count, but I don't understand gc_tel and GENOME_LENGTH_AT_TEL_GC (which is defined as 332720800, about 1/10 of the human haploid chromosome ). If you can clarify then it should be easy to convert the results to another organism.

Best Regards,
Ray

**Comment by zd1** [comment]
Dear Ray, 
Thanks for your interest in using telseq. 

`gc_tel` is the number of reads that have their GC composition in the same range as the telomeres. This is set to be 48%-52% here
https://github.com/zd1/telseq/blob/48c2ebcf2694a8396d96b3502a5188b9075ddba6/src/Telseq/telseq.h#L41
The human telomere repeat unit TTAGGG or CCCTAA has a GC composition of exact 50%. We extend that to allow for technical variation. 

GENOME_LENGTH_AT_TEL_GC is the cumulative length of the reference genome that has a GC composition in the defined range. It is generated by (1) splitting the reference genome into sequential segments in same length as the sequence read, e.g. 100bp, and then (2) count up how many of them have the GC in the defined range and convert that back into length. 

Hope that clarifies it a little, 

Thanks,
Zhihao

**Comment by melop** [comment]
Dear Zhihao,

thank you for the detailed information. I'm assuming that gc_tel will be computed from the bam file, but GENOME_LENGTH_AT_TEL_GC is what I need to compute on my own, is that correct?

Ray

**Comment by zd1** [comment]
Yes, that's right. 
As a start, for simplicity, it could be just set to the length of the reference genome. 

Best,
Zhihao

**Comment by melop** [comment]
Em... A bit confused, the GENOME_LENGTH_AT_TEL_GC value is only about 10% of the reference genome size. If you plug the reference genome size directly into the formula wouldn't that inflate the estimate by 10 fold?

**Comment by zd1** [comment]
Yes, it would, but can be scaled back once the number becomes available.

**Comment by melop** [comment]
Dear Zhihao, I want to now write a script to calculate GENOME_LENGTH_AT_TEL_GC for my reference genome. Just a few more technical questions, How do I deal with "N"'s? Also, if the reads in my dataset is 150 x 2, should I use a window of 100bp or 150bp, given that the program was run on the bam files with the default settings?

**Comment by zd1** [comment]
Sure. The Ns at the ends could be added to the length but you may want to skip the Ns in the middle of a chromsome. For the read length, just increase the step size to 150. When running telseq, you could try to increase -k a bit as there are now more repeats in a read, but the default should be fine as well.
