### ISSUE TITLE
Bamtools Not Found

### ISSUE THREAD

**Issue by jerryyyyy** [zd1/telseq#16]
Hello, I am having a similar error to hat has been reported for the ./configure. 

 I have installed Bamtools and I can see the libraries in /usr/local/include/bamtools/api.

I have tried several variants of:

xxxx@ubuntu:~/Downloads/telseq-master/src$ ./configure --with-bamtools=/usr/local/include

xxxxxxx@ubuntu:~/Downloads/telseq-master/src$ ./configure --with-bamtools=/usr/local/include
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/home/xxxxxxx/Downloads/telseq-master/src/missing: Unknown `--is-lightweight' option
Try `/home/xxxxxxx/Downloads/telseq-master/src/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for ranlib... ranlib
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking api/BamReader.h usability... no
checking api/BamReader.h presence... no
checking for api/BamReader.h... no
configure: error: The bamtools library must be installed (http://github.com/pezmaster31/bamtools). You can specify its path with the --with-bamtools=PATH option

Nay help appreciated!

**Comment by jerryyyyy** [comment]
Boy, I have tried every PATH combo in the Free World and still; cannot get this to work!

**Comment by zd1** [comment]
Hi there, 

Thanks for trying to use telseq. Could you try

./configure --with-bamtools=/usr/local/include/bamtools

Zhihao

**Comment by jerryyyyy** [comment]
Thanks for responding.   Here is the full result... looks like there is something more basic at the top...
XXX@ubuntu:~/Downloads/telseq-master/src$ ./configure --with-bamtools=/usr/local/include/bamtools
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/home/yesavage/Downloads/telseq-master/src/missing: Unknown `--is-lightweight' option
Try `/home/yesavage/Downloads/telseq-master/src/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for ranlib... ranlib
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking api/BamReader.h usability... no
checking api/BamReader.h presence... no
checking for api/BamReader.h... no
configure: error: The bamtools library must be installed (http://github.com/pezmaster31/bamtools). You can specify its path with the --with-bamtools=PATH option

**Comment by zd1** [comment]
This could be due to bamtools compiled with a different compiler. Would you mind doing the following?

1. set the env variables
export CXX=/path/to/gcc/gcc-4.8.1/bin/g++
export CC=/path/to/gcc/gcc-4.8.1/bin/gcc

2. install bamtools again (not to a system location)

3. install telseq against the above installed bamtools

Zhihao

**Comment by jerryyyyy** [comment]
I think you are on to something.  When I check I am using gg version 6.3.0 (Ubuntu 6.3.0-12).  

 

The director path /usr/gin/gcc just leads to a set of links.  So it is not clear how I can follow those instructions.

**Comment by zd1** [comment]
OK. Looks like the system compiler is found first in path. Let's try 2 and 3.

**Comment by jerryyyyy** [comment]
Thanks for the response.  
I installed bamtools into a special directory:
/programinstallers/bamtools/src/api
As far as I can see all the libraries and .h files are in there.
It never gets to the compilation because it never gets through the ./configure step... that is where it checks for the .h files and dies.  
I have rewritten the $PATH variable multiple times as well as use the ./configure --with-bamtools=/programinstallers/bamtools/src/api (and multiple variants of this).....
We still get the same error.....:

checking for unistd.h... yes
checking api/BamReader.h usability... no
checking api/BamReader.h presence... no
checking for api/BamReader.h... no
configure: error: The bamtools library must be installed (http://github.com/pezmaster31/bamtools). You can specify its path with the --with-bamtools=PATH option
