### ISSUE TITLE
Docker Version

### ISSUE THREAD

**Issue by jerryyyyy** [zd1/telseq#17]
Have been trying to use the docker version with:

docker build -t telseq-docker github.com/zd1/telseq

But getting errors on W10 docker:

Unable to build context:  Unable to find 'git':  exec: "git": executable file not found in "%PATH%

Suggestions appreciated.

**Comment by zd1** [comment]
Looks like git hasn't been installed? Would you be able to find the executable by command 
"which git" ?

Alternatively, just download the "Dockerfile" in the repo
https://github.com/zd1/telseq/blob/master/Dockerfile

and then build docker image by running against the downloaded file as below (replace the path with the downloaded path)

docker build -t telseq-docker /path/to/my/downloaded/Dockerfile

**Comment by jerryyyyy** [comment]
I am new to docker and installed it in Windows, so I am running in the command screen of a Windows installation of docker.  

The prompt is for a Windows system, e.g C:\WINDOWS\system32

which get is not recognized.

Looks like I have to install a Linux version of docker in my linux VM?  

Starting down that road.

**Comment by jerryyyyy** [comment]
Good news I got it installed in my Ubuntu Virtual Machine and it runs...  Of course then it no longer sees the genetics files mounted in Windows.  Apparently I have to update the VMware Tools....  not a piece of cake.

**Comment by jerryyyyy** [comment]
This VMware problem looks like a mess:

https://stackoverflow.com/questions/39858200/vmware-workstation-and-device-credential-guard-are-not-compatible

All stopped working after the latest set on W10 updates....  If you do not have Hyper-V, no files shared, it appears.  But with Hyper-V VMware does not start correctly.  

I better try to put it on a real Linux box.  This is not easy as all the Linux boxes we have are locked down carefully for security reasons. I was trying to do this data analysis on an isolated system.

**Comment by jerryyyyy** [comment]
Reopening, not clear about this commenting system.
