### ISSUE TITLE
Can telseq be used for custom panels?

### ISSUE THREAD

**Issue by dilmiperera** [zd1/telseq#18]
Hi Zhihao,

I was wondering if telseq can be used for sequencing data from custom panels (not WGS or WES)? If so, which parameters would I need to change (k value maybe)?

Thanks, 
Dilmi

**Comment by zd1** [comment]
Hi Dilmi, 

Thanks for your interests in telseq. I haven't evaluated on data from customised panels so don't know if it would work. Telseq relies on off-target reads for telomere information, so it depends on whether there are any such reads in the output. read-length is also important as it would affect what k could be used, as how many TTAGGG/CCCTAA can a read possibly contain. 

Having said that, if there are telomeric reads in the output, there's nothing wrong with trying to use it. I think having matched controls that are assayed using the same or similar protocols would be a good idea. 

Best,
Zhihao
