### ISSUE TITLE
Recommendation of k for 35bp and 49bp reads

### ISSUE THREAD

**Issue by SiyangLiu** [zd1/telseq#19]
Hi Zhihao,
I have thousands of low coverage whole genome sequencing samples with either 35bp or 49bp illumina single end reads.
I tired different k and hereby enclose an excel file in the attachment. 
[telseq_35bp_differentk.xlsx](https://github.com/zd1/telseq/files/1680271/telseq_35bp_differentk.xlsx)

What k would you recommend based on this estimation? It seems that none of the k produces the expected length estimation 5kbp - 15kbp. Could you provide me with some advice how to estimate telomere length with this data? 

I would also like to kindly ask how you decide on the constant GENOME_LENGTH_AT_TEL_GC ? Is the  constant value 332, 720, 800bp relevant to the human genome reference I use, like hg19? 

Thanks!

Best,
Siyang

**Comment by zd1** [comment]
Hi Siyang, 

Thanks for your interest in using telseq. 
I don't have much experience with using telseq on 35bp or 49bp libraries. I don't know how it would perform in this case. I would use a high threshold. For example, for a 35bp read, it maximally could have 5 TTAGGG repeats, so I would use k=5 or k=4. Likewise for the 49bp library I would use k=8 or k=7. 

The normalising constant was computed by counting 100bp segments in hg19 that have the telomeric GC composition. So as you see it has the assumption of 100bp reads. I would recommend comparing your estimates of your samples against some controls that are produced using the same or similar protocol.

Best,
Zhihao

**Comment by SiyangLiu** [comment]
Thanks Zhihao!  I am still worried about the short telomere length estimated by our data (2-3kbp using k=5 and k=4) when compared to the expectation 5kbp - 15kbp. 
Do you think re-estimate the normalising constant by counting 35bp segments in hg19 will help? Should I try? When you are estimating the GC content, are you using an absolute window or a sliding window? If you are using the sliding window, what is the step size?
Could you tell me more about why you think "comparing my estimates of my samples against some controls that are produced using the same or similar protocol? " will help? Does the controls refer to samples with 100bp reads or with higher sequencing depth?
Look forward to your reply.
Thanks!

**Comment by zd1** [comment]
Hi, you could try re-calibrating the normalisation constant but I am not sure if that'd be helpful. It's a rough estimate of the proportion of the genome that is dense in TTAGGG. When computing this, I took each window one after another without any overlap between them - so it wasn't a sliding-window approach.  

I didn't mean comparing against samples produced using a separate protocol, e.g. 100bp reads. Comparing against results from high depth data for same samples could be useful if that's possible. 

Best,
Zhihao
