### ISSUE TITLE
location of files needed if bamtools path is not functioning

### ISSUE THREAD

**Issue by jamesdalg** [zd1/telseq#20]
What specific files are needed to copy over to make telseq work? I'm on a cluster (one of the largest in the world) and can't get admin access. I tried using the bamtools paths, but to no avail.
bash-4.1$ ./configure --with-bamtools=/usr/local/apps/bamtools/2.4.1/lib --prefix=bash-4.1$ ./configure --with-bamtools=/usr/local/apps/bamtools/2.4.1/lib
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: ./configure
configure: error: expected an absolute directory name for --prefix: bash-4.1$
bash-4.1$ ./configure --with-bamtools=/usr/local/apps/bamtools/2.4.1/lib/ --prefix=/usr/local/apps/bamtools/2.4.1/lib/
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for ranlib... ranlib
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... no
checking for sys/types.h... no
checking for sys/stat.h... no
checking for stdlib.h... no
checking for string.h... no
checking for memory.h... no
checking for strings.h... no
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... no
checking api/BamReader.h usability... no
checking api/BamReader.h presence... yes
configure: WARNING: api/BamReader.h: present but cannot be compiled
configure: WARNING: api/BamReader.h:     check for missing prerequisite headers?
configure: WARNING: api/BamReader.h: see the Autoconf documentation
configure: WARNING: api/BamReader.h:     section "Present But Cannot Be Compiled"
configure: WARNING: api/BamReader.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------ ##
configure: WARNING:     ## Report this to zhihao.ding@gmail.com ##
configure: WARNING:     ## ------------------------------------ ##
checking for api/BamReader.h... no
configure: error: The bamtools library must be installed (http://github.com/pezmaster31/bamtools). You can specify its path with the --with-bamtools=PATH option

**Comment by jerryyyyy** [comment]
Hi, I got this to work about 2 months ago and am back in the same boat with a new install.  I have admin privileges but my bamtools install does not seem to put the libraries in the right spot (I cannot find them) in the format/location required, in other words, I do not find the proper directories to be referenced in the ./configure script.  

The /usr/local/include/bamtools has /shared and /api directories now... 

>>>>>>>>>>>>>>>>>>> your instructions

The executable binary will be at src/Telseq/telseq. If bamtools are installed not at the system location, you can specify their location by

./configure --with-bamtools=/path/to/bamtools

The /path/to/bamtools directory is the directory that contains 'lib' and 'include' sub directories.

**Comment by jerryyyyy** [comment]
Hi, got this to work.  The install wound up in a directory that surprised me and the machine....

**Comment by zd1** [comment]
OK, that's great
