### ISSUE TITLE
Quick question: counting of aligned vs unaligned reads

### ISSUE THREAD

**Issue by jamesdalg** [zd1/telseq#21]
With telseq, are unaligned reads counted as well as aligned reads with bam input?
"Total   Mapped  Duplicates" are given in the output.
The source code would suggest that these reads are skipped, so I'm just trying to determine if they are counted. Telomeric sequences are frequently unmappable and I'm trying to determine what set of reads is counted in the statistics, for reporting purposes.

// skip reads with readgroup not defined in BAM header
    if(resultmap.find(tag) == resultmap.end()){
      std::cerr << "RG tag {" << tag << "} for read at position ";
      std::cerr << "{" << record1.RefID << ":" << record1.Position << "} doesn't exist in BAM header.";
      continue;
    }

**Comment by zd1** [comment]
Hi there, 

Thanks for your interest in telseq and sorry for the delayed reply. 

All reads are counted toward computing the result regardless of whether they are mapped. The numbers of the mapped reads and duplicated reads are only there for information. They can give a sense on the production quality of a sequencing library. You are right that duplication and mappability should not contribute to the results. 

The code in quote there is for selecting reads for a given sample. It is not skipping the unmapped reads.

Thanks,
Zhihao
