### ISSUE TITLE
Support for multiple telomeric repeats and faster run time

### ISSUE THREAD

**Issue by fpbarthel** [zd1/telseq#6]
Hi,

You may be interested in the following: http://stackoverflow.com/questions/36360005/c-multiple-string-matching-without-using-regex and http://stackoverflow.com/questions/16850992/call-a-c-function-from-c-code. With help from others (I am complete C newbie) I modified the telseq program to support multiple telomeric repeats and rewrote the countMotif() function in C99. This actually improved Telseq performance to run a little faster compared to the original version.

Thanks

**Comment by zd1** [comment]
Thanks for the link and efforts to improve the code!

Zhihao

**Comment by fpbarthel** [comment]
As a comparison, for the same 120 GB WGS BAM:
- Original TelSeq, C++ countMotif, one pattern string "TTAGGG" and reverse complement: CPU time 7450.10s
- Modified TelSeq, C99 countMotif, four pattern strings (TTAGGG, TGAGGG, TCAGGG, TTGGGG) and reverse complements: CPU time 6391.94s

The difference is also noticeable using the test.2.bam from the Test/ folder. The modified TelSeq has an average CPU time of 0.02s and the original TelSeq of 0.03s.

P.s. the 120 GB bam is stored on a storage drive and I/O is a large speed bottleneck

**Comment by fpbarthel** [comment]
Also, not sure if you are aware, the addition of multiple telomeric patterns was inspired by the recently released package telomere hunter. Never tried their package but it's python so I suspect it's not as fast. https://pypi.python.org/pypi/telomerehunter/

**Comment by zd1** [comment]
Thanks for the comparison. I agree that this computing is often IO bound. I am not aware of the python package you mentioned, thanks for the reference. 

Zhihao
