### ISSUE TITLE
telseq on exome sequencing data

### ISSUE THREAD

**Issue by ikramu** [zd1/telseq#7]
Dear Zhihao,

I want to investigate telomere patterns in my exome sequencing data. As I understand from Telseq paper, the software is mainly built for WGS data with possible applications for exome sequencing data in the cases where the off-target sequences contains the telomere sequences. 
In this regard, I was wondering if there are any special flags I need to set when checking telseq on my exome sequencing data. 

Thanks!

**Comment by zd1** [comment]
Hi, thanks for your interests in telseq. If the samples were sequenced using a same protocol, no flag should be needed. Otherwise it could help capping the depth in the exonic regions. Having said that, the best thing to do is still having controls in each condition. 

Cheers,
Zhihao

**Comment by ikramu** [comment]
Hi Zhihao,

Thanks for your reply.

Yes, All the sequencing was performed using the same protocol, i.e., same Agilent kit was used for target enrichment while same Illumina HiSeq 2500 platform was used for pair-end sequencing.

Cheers,
Ikram

**Comment by diphro** [comment]
Hi,

I'm also trying to calculate telomere length using exome data.

But the length estimated is very low: ~0.2kb for k=7 and  ~0.5kb for k=5 (read length = 75)
With exome bam files of another project I also obtain results <1base (0.0005kb) for k=7 (read length = 75)
However, using WGS data I find more consistent results (~10kb)

@zd1 I'm wondering if the telomere length estimation works only using specific exome capture protocole? Maybe the "10-50% of sequences off-target" used to estimate the telomere length is lower with new capture protocoles?

@ikramu can you give me a order of magnitude of the estimated length you obtained with your exome data?

Cheers,
Quentin.

**Comment by zd1** [comment]
Hi Quentin,

  Sorry for delayed reply. I haven't done any systematic evaluation on
  data produced from different exome protocols. I am afraid I can't
  provide useful feedback. I think it's a good idea to compare samples
  assayed by similar protocols, e.g. having controls in same batches.

  Best,
  Zhihao
