### ISSUE TITLE
UNKNOWN length estimate using exome sequencing data

### ISSUE THREAD

**Issue by ikramu** [zd1/telseq#9]
Hi,

I am using telseq on exome sequencing data using the following command

telseq -e ~/Downloads/telseq/targets.bed -f ~/Downloads/telseq/fileList.txt ~/Downloads/telseq/telseqOutput.txt
In the output, although I get estimates for the number of reads at different "k" and GC-adjusted coverage, I am getting UNKNOWN for the length estimate. 

Here is one line from my output
ReadGroup       Library Sample  Total   Mapped  Duplicates      LENGTH_ESTIMATE TEL0    TEL1    TEL2    TEL3    TEL4    TEL5    TEL6    TEL7    TEL8    TEL9    TEL10   TEL11   TEL12   TEL13   TEL14   TEL15   TEL16   GC0     GC1     GC2     GC3     GC4     GC5     GC6     GC7     GC8     GC9  
0       UNKNOWN Patient10        10743572        10743501        3112566 UNKNOWN 10499798        241583  2140    51      0       0       0       0       0       0       0       0       0
       0       0       0       0       579891  1001440 944504  785288  703376  364539  587419  618909  608799  558685  

Can someone assist me as to where I may be wrong?

Cheers,
Ikram

**Comment by zd1** [comment]
Hi Ikram,

Thanks for your interests in using telseq. It seems that there's no reads
beyond TEL4, meaning reads containing four telomeric repeats. Have you
tried running it without "-e" ?

Cheers,
Zhihao

On 28 June 2016 at 17:17, Ikram Ullah notifications@github.com wrote:

> Hi,
> 
> I am using telseq on exome sequencing data using the following command
> 
> telseq -e ~/Downloads/telseq/targets.bed -f
> ~/Downloads/telseq/fileList.txt ~/Downloads/telseq/telseqOutput.txt
> In the output, although I get estimates for the number of reads at
> different "k" and GC-adjusted coverage, I am getting UNKNOWN for the length
> estimate.
> 
> Here is one line from my output
> ReadGroup Library Sample Total Mapped Duplicates LENGTH_ESTIMATE TEL0 TEL1
> TEL2 TEL3 TEL4 TEL5 TEL6 TEL7 TEL8 TEL9 TEL10 TEL11 TEL12 TEL13 TEL14 TEL15
> TEL16 GC0 GC1 GC2 GC3 GC4 GC5 GC6 GC7 GC8 GC9
> 
> 0 UNKNOWN Patient10 10743572 10743501 3112566 UNKNOWN 10499798 241583 2140
> 51 0 0 0 0 0 0 0 0 0
> 0 0 0 0 579891 1001440 944504 785288 703376 364539 587419 618909 608799
> 558685
> 
> Can someone assist me as to where I may be wrong?
> 
> Cheers,
> Ikram
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/zd1/telseq/issues/9, or mute the thread
> https://github.com/notifications/unsubscribe/AAxs15cVZ-09BgFJwht3sKk4dfNY6Kseks5qQUkPgaJpZM4JARvb
> .

## 

This email is sent on behalf of Genomics plc, a public limited company 
registered in England and Wales with registered number 8839972, VAT 
registered number 189 2635 65 and registered office at 24 Cornhill, London, 
EC3V 3ND, United Kingdom.
The contents of this e-mail and any attachments are confidential to the 
intended recipient. If you are not the intended recipient please do not use 
or publish its contents, contact Genomics plc immediately at 
info@genomicsplc.com info@genomicsltd.com then delete. You may not copy, 
forward, use or disclose the contents of this email to anybody else if you 
are not the intended recipient. Emails are not secure and may contain 
viruses.

**Comment by ikramu** [comment]
Dear Zhihao, 
Thanks for replying. I will try it without -e and share the output.

By the way, don't we see values for TEL5, TEL6, TEL7, and TEL8 (10499798,  241583, 2140, and 51 respectively)? 

Cheers,
Ikram

**Comment by zd1** [comment]
Sure, there are interstitial telomeric sequences in the genome could give
that quantity. What's needed here is reads with very high density of
repeats.

Cheers,
Zhihao

On 30 June 2016 at 15:11, Ikram Ullah notifications@github.com wrote:

> Dear Zhihao,
> Thanks for replying. I will try it without -e and share the output.
> 
> By the way, don't we see values for TEL5, TEL6, TEL7, and TEL8 (10499798,
> 241583, 2140, and 51 respectively)?
> 
> Cheers,
> Ikram
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/zd1/telseq/issues/9#issuecomment-229670036, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAxs129ZuOfs2IQIEMcPt8tYfoRJEuxzks5qQ85-gaJpZM4JARvb
> .

## 

This email is sent on behalf of Genomics plc, a public limited company 
registered in England and Wales with registered number 8839972, VAT 
registered number 189 2635 65 and registered office at 24 Cornhill, London, 
EC3V 3ND, United Kingdom.
The contents of this e-mail and any attachments are confidential to the 
intended recipient. If you are not the intended recipient please do not use 
or publish its contents, contact Genomics plc immediately at 
info@genomicsplc.com info@genomicsltd.com then delete. You may not copy, 
forward, use or disclose the contents of this email to anybody else if you 
are not the intended recipient. Emails are not secure and may contain 
viruses.
